AWSTemplateFormatVersion: '2010-09-09'
Description: Wordpress Lambda Update security group stack - S3

Parameters:
  Environment:
    Type: String
  Application:
    Type: String
  PreviousBackupsDeletedAfterDays:
    Type: Number

Resources:

  S3BucketArtefact:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      AccessControl: Private
      BucketName:
        Fn::Join:
        - "-"
        - - !Ref Environment
          - !Ref Application
          - artefacts

  S3NestedTemplates:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName:
        Fn::Join:
        - "-"
        - - !Ref Environment
          - !Ref Application
          - nestedtemplates

  S3Backups:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName:
        Fn::Join:
        - "-"
        - - !Ref Environment
          - !Ref Application
          - backups
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldBackupsAfterOneMonth
            NoncurrentVersionExpirationInDays: !Ref PreviousBackupsDeletedAfterDays
            Status: 'Enabled'
      VersioningConfiguration:
        Status: 'Enabled'
